# Generated by Django 4.2.5 on 2023-12-26 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kite',
            old_name='expert',
            new_name='user',
        ),
    ]
