# Generated by Django 4.2.5 on 2024-02-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kites', '0002_rename_expert_kite_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['time_create']},
        ),
        migrations.AddField(
            model_name='expert',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01 00:00'),
            preserve_default=False,
        ),
    ]
